doc: turbo/net plugin is required
Otherwise get error:
```
Running psql
ERROR:  relation "net_http_request" does not exist
LINE 7:         net_http_request,
                ^
```
which is cryptic to the steampipe uninitiated